import React from "react";

const Home = () => {
  return (
    <div className="bg-red-300">
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
    </div>
  );
};

export default Home;
